---
- name: Install GitLab EE
  hosts: all
  become: yes
  tasks:
    - name: Add GitLab EE GPG key
      apt_key:
        url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
        state: present

    - name: Add GitLab EE repository
      apt_repository:
        repo: "deb https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/ {{ ansible_lsb.codename }} main"
        state: present

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install GitLab EE
      apt:
        name: gitlab-ee
        state: latest

    - name: Set external URL
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: '^external_url'
        line: 'external_url "http://127.0.0.1"'

    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure
      args:
        creates: /var/opt/gitlab/bootstrapped