---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name:
      - vim
      - curl
      - git
      - htop
      - net-tools
      - unzip
      - openssh-server
    state: present